In [1]:
import torch

In [2]:
A = torch.randn(2, 3)
A

tensor([[-1.5982, -0.4141,  2.0930],
        [ 0.8375,  0.4116,  0.9243]])

In [3]:
B = torch.randn(3, 4)
B

tensor([[-0.1932,  0.0493,  1.4451,  0.6465],
        [-1.3373, -0.8739,  0.1519,  0.4508],
        [ 2.2417, -0.8908,  0.8553,  0.2442]])

In [4]:
C = torch.einsum('ij,jk->ik', A, B)
C

tensor([[ 5.5546, -1.5813, -0.5823, -0.7089],
        [ 1.3596, -1.1417,  2.0634,  0.9528]])

In [5]:
b, q, d_model, n, h = 2, 5, 8, 2, 4  # d_model must equal n*h
x = torch.randn(b, q, d_model)
w_q = torch.randn(d_model, n, h)

q = torch.einsum("bqd,dnh->bqnh", x, w_q)
print(q.shape)  # torch.Size([2, 5, 2, 4])

torch.Size([2, 5, 2, 4])


In [ ]:
weight = torch.tensor([[262., 330., 116., 325.], [231., 280., 516., 129.]])
print(weight.float().sort(dim=-1, descending=True).values)
# print(weight.float().sort(dim=2, descending=True).values)
# weight.float().sort(dim=1, descending=True).indices

tensor([[330., 325., 262., 116.],
        [516., 280., 231., 129.]])


IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)